name: GreenCI Live Validation

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Simulate build
        run: sleep 10

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Simulate tests
        run: sleep 60

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Simulate lint
        run: sleep 5

  greenci:
    name: GreenCI
    if: always()
    needs:
      - build
      - test
      - lint

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      pull-requests: write

    steps:
      - name: Analyze CI
        uses: tjrgus2/GreenCI@c85bdc0ce8c8245fb92a7b912157038f8f32a753
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
